config/routes.rb
# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  get 'health_check', to: 'health_check/health_check#index'

  # Error routes.
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_error', via: :all

  # Signup routes.
  get '/signup', to: 'users#new', as: :signup
  post '/signup', to: 'users#create', as: :create_user

  # Redirect to terms page
  match '/terms', to: 'users#terms', via: [:get, :post]

  # Password reset resources.
  resources :password_resets, only: [:new, :create, :edit, :update]

  # User resources.
  scope '/u' do
    # Verification Routes
    scope '/verify' do
      match '/resend', to: 'users#resend', via: [:get, :post], as: :resend
      match '/confirm/:user_uid', to: 'users#confirm', via: [:get, :post], as: :confirm
    end

    # Handles login of greenlight provider accounts.
    post '/login', to: 'sessions#create', as: :create_session

    # Log the user out of the session.
    get '/logout', to: 'sessions#destroy'

    # Account management.
    get '/:user_uid/edit', to: 'users#edit', as: :edit_user
    patch '/:user_uid/edit', to: 'users#update', as: :update_user
    delete '/:user_uid', to: 'users#destroy', as: :delete_user
  end

  # Handles Omniauth authentication.
  match '/auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post], as: :omniauth_session
  get '/auth/failure', to: 'sessions#omniauth_fail'

  # Room resources.
  resources :rooms, only: [:create, :show, :destroy], param: :room_uid, path: '/'

  # Extended room routes.
  scope '/:room_uid' do
    post '/', to: 'rooms#join'
    patch '/', to: 'rooms#update', as: :update_room
    post '/start', to: 'rooms#start', as: :start_room
    get '/logout', to: 'rooms#logout', as: :logout_room

    # Manage recordings
    scope '/:record_id' do
      post '/', to: 'rooms#update_recording', as: :update_recording
      delete '/', to: 'rooms#delete_recording', as: :delete_recording
    end
  end

  root to: 'main#index'
end

app/views/shared/modals/_create_room_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="modal fade" id="createRoomModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-6">
          <div class="card-title">
            <h3><%= t("modal.create_room.title") %></h3>
          </div>

          <%= form_for(:room, url: rooms_path) do |f| %>
            <div class="input-icon">
              <span class="input-icon-addon">
                <i class="fas fa-chalkboard-teacher"></i>
              </span>
              <%= f.text_field :name, id: "room-name", class: "form-control", value: "", placeholder: t("modal.create_room.name_placeholder"), autocomplete: :off %>
              <div class="invalid-feedback text-left"><%= t("modal.create_room.not_blank") %></div>
            </div>
            <label class="custom-switch mt-5 mb-5 float-left">
              <%= f.check_box :auto_join, class: "custom-switch-input", checked: false %>
              <span class="custom-switch-indicator"></span>
              <span class="custom-switch-description"><%= t("modal.create_room.auto_join") %></span>
            </label>
          <div class="form-footer">
            <%= f.submit t("header.create_room"), id: "create-room-submit", class: "btn btn-outline-primary btn-block btn-pill" %>
          </div>
          <% end %>
        </div>
        <div class="card-footer">
          <p><%= t("modal.create_room.free_delete") %></p>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
// Handle validation messages client-side because
// form is served in modal, and they are minimal.
var roomCreateValidations = function(){
  if($('#room-name').val().length == 0){
    $('#room-name').addClass("is-invalid");
  }
}

$('#create-room-submit').on('click', roomCreateValidations);
</script>

app/views/shared/modals/_delete_account_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="modal fade" id="deleteAccountModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-6">
          <div class="card-title">
            <h3><%= t("modal.delete_account.confirm") %></h3>
          </div>

          <button type="button" class="btn btn-pill btn-info my-1 btn-del-room" data-dismiss="modal">
            <%= t("modal.delete_account.keep") %>
          </button>

          <%= button_to delete_user_path, method: :delete, id: "delete-confirm", class: "btn btn-pill btn-danger my-1 btn-del-room" do %>
            <%= t("modal.delete_account.delete") %>
          <% end %>

        </div>
        <div class="card-footer">
          <p><%= t("modal.delete_account.warning").html_safe %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/modals/_delete_room_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="modal fade" id="deleteRoomModal_<%= room.uid %>" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-6">
          <div class="card-title">
            <h3><%= t("modal.delete_room.confirm", room: room.name) %></h3>
          </div>

          <button type="button" class="btn btn-pill btn-info my-1 btn-del-room" data-dismiss="modal">
            <%= t("modal.delete_room.keep") %>
          </button>

          <%= button_to room, method: :delete, id: "delete-confirm", class: "btn btn-pill btn-danger my-1 btn-del-room" do %>
            <%= t("modal.delete_room.delete") %>
          <% end %>

        </div>
        <div class="card-footer">
          <p><%= t("modal.delete_room.warning").html_safe %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/modals/_login_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="modal fade" id="loginModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-6">
          <div class="card-title">
            <h3><%= t("login") %></h3>
          </div>
          <% unless iconset_providers.length.zero? %>
            <% iconset_providers.each do |provider| %>
              <%= link_to omniauth_login_url(provider), class: "customBtn-#{provider}" do %>
                <span class="customBtn-icon">
                  <img class="customBtn-image"></img>
                </span>
                <span class="customBtn-text"><%= t("modal.login.with", provider: t("provider.#{provider}")) %></span>
              <% end %>
            <% end %>
            <div class="or-line my-6">
              <div>
                <span class="text-uppercase">
                  <%= t("modal.login.or") %>
                </span>
              </div>
            </div>
          <% end %>
          <%= form_for(:session, url: create_session_path) do |f| %>
            <div class="form-group">
              <div class="input-icon">
                <span class="input-icon-addon">
                  <i class="fas fa-at"></i>
                </span>
                <%= f.text_field :email, class: "form-control", placeholder: t("email"), value: "" %>
              </div>
            </div>
            <div class="form-group">
              <div class="input-icon">
                <span class="input-icon-addon">
                  <i class="fas fa-key"></i>
                </span>
                <%= f.password_field :password, class: "form-control", placeholder: t("password"), value: "" %>
              </div>
            </div>
            <% if Rails.configuration.enable_email_verification %>
              <div class="form-group">
                <div class="input-icon">
                  <%= link_to t("modal.login.forgot_password"), new_password_reset_path %>
                </div>
              </div>
            <% end %>
            <div class="form-footer">
              <%= f.submit t("login"), class: "btn btn-outline-primary btn-block btn-pill" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>