config/routes.rb
# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  get 'health_check', to: 'health_check/health_check#index'

  # Error routes.
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_error', via: :all

  # Signup routes.
  get '/signup', to: 'users#new', as: :signup
  post '/signup', to: 'users#create', as: :create_user

  # Redirect to terms page
  match '/terms', to: 'users#terms', via: [:get, :post]

  # Password reset resources.
  resources :password_resets, only: [:new, :create, :edit, :update]

  # User resources.
  scope '/u' do
    # Verification Routes
    scope '/verify' do
      match '/resend', to: 'users#resend', via: [:get, :post], as: :resend
      match '/confirm/:user_uid', to: 'users#confirm', via: [:get, :post], as: :confirm
    end

    # Handles login of greenlight provider accounts.
    post '/login', to: 'sessions#create', as: :create_session

    # Log the user out of the session.
    get '/logout', to: 'sessions#destroy'

    # Account management.
    get '/:user_uid/edit', to: 'users#edit', as: :edit_user
    patch '/:user_uid/edit', to: 'users#update', as: :update_user
    delete '/:user_uid', to: 'users#destroy', as: :delete_user
  end

  # Handles Omniauth authentication.
  match '/auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post], as: :omniauth_session
  get '/auth/failure', to: 'sessions#omniauth_fail'

  # Room resources.
  resources :rooms, only: [:create, :show, :destroy], param: :room_uid, path: '/'

  # Extended room routes.
  scope '/:room_uid' do
    post '/', to: 'rooms#join'
    patch '/', to: 'rooms#update', as: :update_room
    post '/start', to: 'rooms#start', as: :start_room
    get '/logout', to: 'rooms#logout', as: :logout_room

    # Manage recordings
    scope '/:record_id' do
      post '/', to: 'rooms#update_recording', as: :update_recording
      delete '/', to: 'rooms#delete_recording', as: :delete_recording
    end
  end

  root to: 'main#index'
end

app/views/shared/_error_banner.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="alert alert-icon alert-danger text-center mb-0">
  <%= yield %>
</div>

app/views/shared/_features.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>


<div class="container mt-8 mb-6 text-center">

  <h2 class="mb-6">Greenlight <%= t("features.title") %></h2>

  <div class="row feature-stamp">
    <div class="col-lg-3 col-md-6">
      <div class="feature-item">
        <div class="stamp bg-primary"><i class="fas fa-chalkboard-teacher fa-2x"></i></div>
        <h4 class="mt-4"><%= t("features.rooms") %></h4>
      </div>
    </div>
    <div class="col-lg-3 col-md-6">
      <span class="stamp bg-primary"><i class="fas fa-film fa-2x"></i></span>
      <h4 class="mt-4"><%= t("features.recordings") %></h4>
    </div>
    <div class="col-lg-3 col-md-6">
      <span class="stamp bg-primary"><i class="fas fa-pencil-alt fa-2x"></i></span>
      <h4 class="mt-4"><%= t("features.designs") %></h4>
    </div>
    <div class="col-lg-3 col-md-6">
      <span class="stamp bg-primary"><i class="fas fa-door-open fa-2x"></i></span>
      <h4 class="mt-4"><%= t("features.authentication") %></h4>
    </div>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key} d-inline-block text-success" %>
<% end %>

app/views/shared/_footer.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<footer class="footer pt-3">
  <p class="text-center mb-1"><%= t("footer.powered_by", href: link_to(t("greenlight"), "https://bigbluebutton.org/2018/07/09/greenlight-2-0/", target: "_blank")).html_safe %> v <%= Greenlight::Application::VERSION %></p>
</footer>

app/views/shared/_header.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="header py-4">
	<div class="container">
		<div class="d-flex">
			<%= link_to (current_user ? current_user.main_room : root_path), class: "header-brand" do %>
				<%= image_tag(Rails.configuration.branding_image.blank? ? "logo_with_text.png" : Rails.configuration.branding_image,
					class: "header-brand-img") %>
			<% end %>

			<div class="d-flex ml-auto">
				<% if current_user %>
					<a class="px-5 ml-2 mt-1" href="" data-toggle="modal" data-target="#createRoomModal">
						<i class="fas fa-plus"></i>&nbsp; <%= t("header.create_room") %>
					</a>
					<div class="dropdown">
						<a href="#" class="nav-link pr-0" data-toggle="dropdown">
							<% if current_user.image.blank? %>
								<span class="avatar"><%= current_user.name.first %></span>
							<% else %>
								<span class="avatar" style="background-image: url(<%= current_user.image %>)"></span>
							<% end %>
							<span class="ml-2 d-none d-lg-block">
								<span class="text-default username"><%= current_user.name %></span>
							</span>
						</a>
						<div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow" x-placement="bottom-end">
							<%= link_to current_user.main_room, class: "dropdown-item" do %>
								<i class="dropdown-icon fas fa-home"></i> <%= t("header.dropdown.home") %>
							<% end %>
							<%= link_to edit_user_path(current_user), class: "dropdown-item" do %>
								<i class="dropdown-icon fas fa-cog"></i> <%= t("header.dropdown.settings") %>
							<% end %>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="http://docs.bigbluebutton.org/install/greenlight-v2.html" target="_blank">
								<i class="dropdown-icon far fa-question-circle"></i> <%= t("header.dropdown.help") %>
							</a>
							<%= link_to logout_path, class: "dropdown-item" do %>
								<i class="dropdown-icon fas fa-sign-out-alt"></i> <%= t("header.dropdown.signout") %>
							<% end %>
						</div>
					</div>
				<% else %>
          <% if Rails.configuration.omniauth_bn_launcher %>
            <%= link_to t("login"), omniauth_login_url(:bn_launcher), :class => "btn btn-pill btn-outline-primary mx-2" %>
          <% elsif Rails.configuration.omniauth_ldap %>
						<%= link_to t("login"), omniauth_login_url(:ldap), :class => "btn btn-pill btn-outline-primary mx-2" %>
					<% else %>
            <%= link_to t("login"), "#loginModal", :class => "btn btn-pill btn-outline-primary mx-2", "data-toggle": "modal" %>
          <% end %>

					<% if allow_user_signup? %>
						<%= link_to t("signup.title"), signup_path, :class => "btn btn-pill btn-outline-primary mx-2" %>
					<% end %>

					<%= render "shared/modals/login_modal" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/shared/_room_event.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="background pb-9" room="<%= @room.uid %>" join-name="<%= @join_name %>">
  <div class="container">
    <div class="row pt-9">
      <div class="col-lg-12 col-sm-12">
        <h4 class="text-left"><%= t("room.invited") %></h4>
        <h1 class="display-3 text-left mb-3 font-weight-400"><%= @room.name %></h1>
        <hr class="mt-2 float-left w-25">
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6 col-md-8 col-sm-12 form-inline mb-5 align-top">
        <% if @room.owner.image.blank? %>
          <span class="avatar"><%= @room.owner.name.first %></span>
        <% else %>
          <span class="avatar" style="background-image: url(<%= @room.owner.image %>)"></span>
        <% end %>
        <h5 class="font-weight-normal ml-4 mt-3"><%= @room.owner.name %> (<%= t("room.owner") %>)</h5>
      </div>

      <div class="col-lg-6 col-md-4 col-sm-12">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/sessions", recordings: @room.public_recordings, only_public: true %>

app/views/shared/_sessions.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="sessions pb-5">
  <div class="container pt-6">

    <%= render "shared/components/subtitle", subtitle: (only_public ? t("recording.visibility.public") + " " : "") + t("room.recordings"), search: true %>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="table-responsive">
            <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
              <thead>
                <tr>
                  <th data-header="<%= t("recording.table.name") %>" data-order="none"><%= t("recording.table.name") %></th>
                  <% if recording_thumbnails? %>
                    <th><%= t("recording.table.thumbnails") %></th>
                  <% end %>
                  <th class="text-left" data-header="<%= t("recording.table.length") %>" data-order="none">
                    <%= t("recording.table.length") %>
                  </th>
                  <th class="text-left" data-header="<%= t("recording.table.users") %>" data-order="none">
                    <%= t("recording.table.users") %>
                  </th>
                  <th class="text-left"><%= t("recording.table.visibility") %></th>
                  <th><%= t("recording.table.formats") %></th>
                  <% unless only_public %>
                    <th class="text-center"><i class="icon-settings"></i></th>
                  <% end %>
                </tr>
              </thead>
              <tbody id="recording-table">
                <tr id="no_recordings_found" style="display: none;">
                  <td colspan="7" class="text-center h4 p-6 font-weight-normal" >
                    <%= t("recording.no_matched_recordings", inject: only_public ? t("recording.visibility.public").downcase + " "  : "") %>
                  </td>
                </tr>
                <% if recordings.empty? %>
                  <tr>
                    <td colspan="7" class="text-center h4 p-6 font-weight-normal">
                      <%= t("recording.no_recordings", inject: only_public ? t("recording.visibility.public").downcase + " "  : "") %>
                    </td>
                  </tr>
                <% else %>
                  <% recordings.each do |recording| %>
                    <% if only_public %>
                      <%= render "shared/components/public_recording_row", recording: recording %>
                    <% else %>
                      <%= render "shared/components/recording_row", recording: recording %>
                    <% end %>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>