config/routes.rb
# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  get 'health_check', to: 'health_check/health_check#index'

  # Error routes.
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_error', via: :all

  # Signup routes.
  get '/signup', to: 'users#new', as: :signup
  post '/signup', to: 'users#create', as: :create_user

  # Redirect to terms page
  match '/terms', to: 'users#terms', via: [:get, :post]

  # Password reset resources.
  resources :password_resets, only: [:new, :create, :edit, :update]

  # User resources.
  scope '/u' do
    # Verification Routes
    scope '/verify' do
      match '/resend', to: 'users#resend', via: [:get, :post], as: :resend
      match '/confirm/:user_uid', to: 'users#confirm', via: [:get, :post], as: :confirm
    end

    # Handles login of greenlight provider accounts.
    post '/login', to: 'sessions#create', as: :create_session

    # Log the user out of the session.
    get '/logout', to: 'sessions#destroy'

    # Account management.
    get '/:user_uid/edit', to: 'users#edit', as: :edit_user
    patch '/:user_uid/edit', to: 'users#update', as: :update_user
    delete '/:user_uid', to: 'users#destroy', as: :delete_user
  end

  # Handles Omniauth authentication.
  match '/auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post], as: :omniauth_session
  get '/auth/failure', to: 'sessions#omniauth_fail'

  # Room resources.
  resources :rooms, only: [:create, :show, :destroy], param: :room_uid, path: '/'

  # Extended room routes.
  scope '/:room_uid' do
    post '/', to: 'rooms#join'
    patch '/', to: 'rooms#update', as: :update_room
    post '/start', to: 'rooms#start', as: :start_room
    get '/logout', to: 'rooms#logout', as: :logout_room

    # Manage recordings
    scope '/:record_id' do
      post '/', to: 'rooms#update_recording', as: :update_recording
      delete '/', to: 'rooms#delete_recording', as: :delete_recording
    end
  end

  root to: 'main#index'
end

app/views/shared/components/_confirm_button.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="btn-list text-right pt-8">
    <%= button_to t("verify.accept"), confirm_path, params: { user_uid: params[:user_uid], email_verified: true }, class: "btn btn-primary btn-space" %>
</div>

app/views/shared/components/_public_recording_row.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<tr>
  <td>
    <div id="recording-title">
      <text>
        <% if recording[:metadata][:name] %>
          <%= recording[:metadata][:name] %>
        <% else %>
          <%= recording[:name] %>
        <% end %>
      </text>
    </div>
    <div class="small text-muted">
      <%= t("recording.recorded_on", date: recording_date(recording[:startTime])) %>
    </div>
  </td>
  <% if recording_thumbnails? %>
    <td>
      <% p = recording[:playbacks].find do |p| p.key?(:preview) end %>
      <% if p %>
        <% p[:preview][:images][:image].each do |img| %>
          <%= image_tag(img[:content].strip, class: "thumbnail px-2") %>
        <% end %>
      <% end %>
    </td>
  <% end %>
  <td id="recording-length" class="text-left">
    <div class="small text-muted text-uppercase">
      <%= t("recording.table.length") %>
    </div>
    <%= recording_length(recording[:playbacks]) %>
  </td>
  <td id="recording-users" class="text-left">
    <div class="small text-muted text-uppercase">
      <%= t("recording.table.users") %>
    </div>
    <%= recording[:participants] %>
  </td>
  <td class="text-left">
    <div class="dropdown">
      <% if recording[:metadata][:"gl-listed"] == "true" %>
        <i class="dropdown-icon fas fa-globe px-2"></i> <%= t("recording.visibility.public") %>
      <% else %>
        <i class="dropdown-icon fas fa-link px-2"></i> <%= t("recording.visibility.unlisted") %>
      <% end %>
    </div>
  </td>
  <td>
    <% p = recording[:playbacks].find do |p| p.key?(:length) end %>
    <% recording[:playbacks].each do |p| %>
      <%= link_to p[:type].capitalize, p[:url], class: "btn btn-sm btn-primary", target: "_blank" %>
    <% end %>
  </td>
</tr>

app/views/shared/components/_recording_row.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<tr>
  <td>
    <div id="recording-title" class="form-inline edit_hover_class" data-recordid="<%= recording[:recordID] %>">
      <text id='recording-text'>
        <% if recording[:metadata][:name] %>
          <%= recording[:metadata][:name] %>
        <% else %>
          <%= recording[:name] %>
        <% end %>
      </text>
      <a><i id="edit-record" class="fa fa-edit align-top ml-2" data-edit-recordid="<%= recording[:recordID] %>"></i></a>
    </div>
    <div class="small text-muted">
      <%= t("recording.recorded_on", date: recording_date(recording[:startTime])) %>
    </div>
  </td>
  <% if recording_thumbnails? %>
    <td>
      <% p = recording[:playbacks].find do |p| p.key?(:preview) end %>
      <% if p %>
        <% safe_recording_images(p[:preview][:images][:image]).each do |img| %>
          <%= image_tag(img[:content].strip, class: "thumbnail px-2") %>
        <% end %>
      <% end %>
    </td>
  <% end %>
  <td id="recording-length" class="text-left" data-full-length="<%=recording[:playbacks].first[:length]%>">
    <%= recording_length(recording[:playbacks]) %>
  </td>
  <td id="recording-users" class="text-left">
    <%= recording[:participants] || "-" %>
  </td>
  <td class="text-left">
    <div class="dropdown">
      <% if recording[:metadata][:"gl-listed"] == "true" %>
        <button class="btn btn-sm btn-secondary dropdown-toggle" data-toggle="dropdown"><i class="dropdown-icon fas fa-globe px-2"></i> <%= t("recording.visibility.public") %></button>
      <% else %>
        <button class="btn btn-sm btn-secondary dropdown-toggle" data-toggle="dropdown"><i class="dropdown-icon fas fa-link px-2"></i> <%= t("recording.visibility.unlisted") %></button>
      <% end %>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= button_to update_recording_path(@room, record_id: recording[:recordID], state: "public"), class: "dropdown-item" do %>
          <i class="dropdown-icon fas fa-globe"></i> <%= t("recording.visibility.public") %>
        <% end %>
        <%= button_to update_recording_path(@room, record_id: recording[:recordID], state: "unlisted"), class: "dropdown-item" do %>
          <i class="dropdown-icon fas fa-link"></i> <%= t("recording.visibility.unlisted") %>
        <% end %>
      </div>
    </div>
  </td>
  <td>
    <% recording[:playbacks].each do |p| %>
      <%= link_to p[:type].capitalize, p[:url], class: "btn btn-sm btn-primary", target: "_blank" %>
    <% end %>
  </td>
  <td class="text-center">
    <div class="item-action dropdown">
      <a href="javascript:void(0)" data-toggle="dropdown" class="icon">
        <i class="fas fa-ellipsis-v px-4"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <% p = recording[:playbacks].find do |p| p.key?(:length) end %>
        <% if p %>
          <a class="dropdown-item email-link" data-pres-link="<%= p[:url] %>"><i class="dropdown-icon far fa-envelope"></i> <%= t("recording.email") %></a>
          <div class="dropdown-divider"></div>
        <% end %>
        <%= button_to delete_recording_path(@room, record_id: recording[:recordID]), method: :delete, class: "dropdown-item" do %>
          <i class="dropdown-icon far fa-trash-alt"></i> <%= t("delete") %>
        <% end %>
      </div>
    </div>
  </td>
</tr>

app/views/shared/components/_resend_button.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="btn-list text-right pt-8">
    <%= button_to t("verify.resend"), resend_path, params: { email_verified: false }, class: "btn btn-primary btn-space" %>
</div>

app/views/shared/components/_room_block.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div id="<%= 'home_room_block' if room == current_user.main_room %>" data-room-uid=<%= room.uid %> class="card">
  <div class="card-body p-1">
    <table class="table table-hover table-vcenter text-wrap table-no-border">
      <tbody class="no-border-top">
        <td>
          <span class="stamp stamp-md bg-cyan">
            <% if room == current_user.main_room %>
              <i class="fas fa-home"></i>
            <% else %>
              <i class="fas fa-chalkboard-teacher"></i>
            <% end %>
          </span>
        </td>
        <td>
          <div id="room-name">
            <h4 contenteditable="false" class="m-0 force-text-normal" ><%= room.name %></h4>
          </div>
          <div id="room-name-editable" style="display: none">
            <input id="room-name-editable-input" class="form-control input-sm w-100 h-4" value="<%= room.name %>">
          </div>
          <div class="small text-muted">
            <% if room.sessions > 0 %>
              <i><%= t("room.last_session", session: recording_date(room.last_session)) %></i>
            <% else %>
              <i><%= t("room.no_sessions") %></i>
            <% end %>
          </div>
        </td>
        <td class="text-right">
          <div class="item-action dropdown">
            <a href="javascript:void(0)" data-toggle="dropdown" class="icon <%= 'invisible' if room == current_user.main_room %>">
              <i class="fas fa-ellipsis-v px-4"></i>
            </a>
            <div class="dropdown-menu">
              <!--
              <%= link_to room, class: "dropdown-item" do %>
                <i class="dropdown-icon fas fa-cog"></i> <%= t("room.settings") %>
              <% end %>
              -->
              <a href="" id="rename-room-button" class="dropdown-item">
                <i class="dropdown-icon far fa-edit"></i> <%= t("rename") %>
              </a>
              <a href="" data-toggle="modal" data-target="#deleteRoomModal_<%= room.uid %>"class="dropdown-item">
                <i class="dropdown-icon far fa-trash-alt"></i> <%= t("delete") %>
              </a>
            </div>
          </div>
        </td>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/components/_subtitle.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="row mt-2">
  <div class="col-9">
    <p class="subtitle"><%= subtitle %></p>
  </div>
  <% if search %>
    <div id="search_bar" class="col-3">
      <div class="input-icon">
        <input type="text" class="form-control btn-pill" placeholder="Search...">
        <span class="input-icon-addon">
        <i class="fas fa-search"></i>
      </span>
      </div>
    </div>
  <% end %>
</div>
<hr class="mt-0">

app/views/shared/components/_terms_button.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="btn-list text-right pt-8">
    <%= button_to t("terms.accept_existing"), terms_path, params: { accept: true }, class: "btn btn-primary btn-space" %>
</div>